### ISSUE TITLE
Spell Selection List

### ISSUE THREAD

**Issue by Odoamar** [fmasa/wfrp-master#119]
Spell list contains spells in alphabetical order what is not easy to track.

Idea:

add label: Lore

add option to changing order by Lore and revert it to alphabetical

optional:
Use dedicated icon for each Lore and Petty Spells

**Comment by fmasa** [comment]
Hi,
are you talking about Character Spells, Compendium Spells, or Compendium Spells in Spell Chooser?

For Character Spells, https://github.com/fmasa/wfrp-master/pull/124 visually groups Spells by Lore.

> optional:
> Use dedicated icon for each Lore and Petty Spells

I would really love that, but I cannot use any official imagery due to copyright, so these may only be somewhat generic icons (such as an eye for Tzeench)

**Comment by Odoamar** [comment]
Hi, 
#124 cover all my needs so great job 👍

Regarding images, I think generic ones are enough. If you need some help with picking them go ahead.
