### ISSUE TITLE
Copy and Paste on Computer ?

### ISSUE THREAD

**Issue by TheoKDK** [fmasa/wfrp-master#189]
Hello,
Maybe this is just a problem for me. I use Bluestack in order to have the application on my computer to be able to complete Talents, skills etc from my pdf of the basic book (In French) to fill in my compendium.

Is there a solution for copying text and pasting it directly into the application? That would save me a lot of time.

**Comment by TheoKDK** [comment]
I'd like to take this opportunity to give you a few ideas that I think could come in handy.

- Be able to sort basic and advanced skills in the compendium or make two tabs inside it
- Being able to import items created directly on NPCs/PCs into the compendium in order to add them.
- Being able to highlight career skills directly in the NPC/PC skills, perhaps with a tick box so that we can quickly see which skills we need to improve.

**Comment by fmasa** [comment]
>  Maybe this is just a problem for me. I use Bluestack in order to have the application on my computer to be able to complete Talents, skills etc from my pdf of the basic book (In French) to fill in my compendium.

This sounds like Bluestack issue (I googled `bluestack copy paste` and there seem to be several issues, take a look at [this Reddit post](https://www.reddit.com/r/BlueStacks/comments/fd5ptk/comment/joftwah/?utm_source=reddit&utm_medium=web2x&context=3))

Alternatively, you may want to try the desktop version of WFRP Master. It still needs more polishing, but all the features should be working. I use it a lot on Linux, and one of my players is using it on macOS during sessions).
Just wait for release 3.14.1, which should be built in 30 minutes. The only missing feature is authentication via Google account, but you can reset the password for your account and the log in with your email and password. You can download the desktop app [from the Download page](https://fmasa.github.io/wfrp-master/download/).

> Be able to sort basic and advanced skills in the compendium or make two tabs inside it

I was thinking about introducing filters, so for Skills you would be able to filter by most fields (show only advanced Skills with Agility Characteristic), because there are many use-cases for this (filtering Spells by Lore etc). Would that work for your use case?

> Being able to highlight career skills directly in the NPC/PC skills, perhaps with a tick box so that we can quickly see which skills we need to improve.

This is something I plan to add to the new Career UI (https://github.com/fmasa/wfrp-master/issues/23)

**Comment by TheoKDK** [comment]
> This sounds like Bluestack issue (I googled bluestack copy paste and there seem to be several issues, take a look at [this Reddit post](https://www.reddit.com/r/BlueStacks/comments/fd5ptk/comment/joftwah/?utm_source=reddit&utm_medium=web2x&context=3))

It's probably linked to Bluestack.

>Alternatively, you may want to try the desktop version of WFRP Master. It still needs more polishing, but all the features should be working. I use it a lot on Linux, and one of my players is using it on macOS during sessions).
Just wait for release 3.14.1, which should be built in 30 minutes. The only missing feature is authentication via Google account, but you can reset the password for your account and the log in with your email and password. You can download the desktop app [from the Download page](https://fmasa.github.io/wfrp-master/download/).

I have tried the PC version that you sent me via the link, but it is impossible for me to install the Windows version... I tried the Mac intel version, same thing. The M1 works though.

> I was thinking about introducing filters, so for Skills you would be able to filter by most fields (show only advanced Skills with Agility Characteristic), because there are many use-cases for this (filtering Spells by Lore etc). Would that work for your use case?

Yes, it would be a great solution, which could be used, as you say, for blessings / spells etc.

> This is something I plan to add to the new Career UI (https://github.com/fmasa/wfrp-master/issues/23)

Ah, I hadn't realised that was already in the pipeline. That's great.

**Comment by ManicModron** [comment]
I discovered the Desktop version just tonight looking through the posts, but I'm having an issue trying to get it started.  As a GM it would be very helpful to me to work on a normal keyboard doing updates and Compendium work.

This is the error I'm getting.  Do you have any advice for getting it going?
![image](https://github.com/fmasa/wfrp-master/assets/164831256/ca8c63f0-134e-4f7e-af6d-c808388f1432)

**Comment by fmasa** [comment]
@ManicModron Currently the desktop version is very experimental and not polished for general use. There are a few standing issues and one of them is the question of the distribution. I would like to prepare this for general availability, but this is likely a matter of months.

See https://github.com/fmasa/wfrp-master/issues/34#issuecomment-1728211470 for more details.

**Comment by fmasa** [comment]
Closing this as there is nothing actionable and there is #34 that is better suited for this discussion :slightly_smiling_face:
