### ISSUE TITLE
Add Condition text to the Conditions tab, and similar issues?

### ISSUE THREAD

**Issue by ChapterGrim** [fmasa/wfrp-master#258]
I'm entirely sure this is possible, given how it's formatted, but at the moment a lot of that sort of peripheral information has had to be manually added to the Traits section, to make the information accessible in the games I run or play in. It's included text of: flaws and qualites, Fate/Fortune and Resilience/ Resolve,  Corruprion (which isn't directly accessible via a tab yet), and is likely to include Injuries and Diseases etc... 🤔

**Comment by fmasa** [comment]
@ChapterGrim I think this might be a perfect use case for the [Journal Entries](https://github.com/fmasa/wfrp-master/pull/199). Some of these are also easy to import from the Rulebook.

So I propose a simple logic for this:
- Rules for supported functionality would be automatically imported as Journal Entries with the corresponding structure to the Rulebook PDF (e.g. for Conditions there would be `Rules / Conditions` journal entry for the summary, `Rules / Conditions / Master Condition List / Bleeding` for *Bleeding* Condition etc
- Some elements (qualities, conditions, ...) will become either clickable or we introduce an icon that opens the appropriate Journal entry on click

> , and is likely to include Injuries and Diseases etc... 🤔

I plan to add explicit support for those so that you can track current Injuries and Diseases for any Character. See https://github.com/fmasa/wfrp-master/issues/19

**Comment by fmasa** [comment]
Closing:
- :heavy_check_mark: Conditions text is already added
- :heavy_check_mark: Weapon/Armour/Ammunition/Item Qualities & Flaws are implemented and will be released in next version
- :heavy_check_mark:  Diseases are implemented
- There is an issue for Injuries - #315
- There is an issue for Mutations - #316 
- There is an issue for points - https://github.com/fmasa/wfrp-master/issues/375

@ChapterGrim Pleae

**Comment by fmasa** [comment]
@ChapterGrim Please open issue for specific item type if you spot anything missing. I can't promise everything will be imported, but the basic stuff is IMO useful.
