### ISSUE TITLE
App crashes and exits on npc tab

### ISSUE THREAD

**Issue by happydoggoo** [fmasa/wfrp-master#362]
When going into the npc tab the app crashes and fully closes

**To Reproduce**
.5 duplicate an npc (something causes a crash here seemingly at random) 
1. Go to load the npc tab
2. Will crash upon attempted load in

**Smartphone (please complete the following information):**
Samsung s20+
 - Android version: 13
 - Device language: English
 - App version: Latest on the play store as of 5 nov
 - App language English

**Additional context**
Starting a new party temporarily fixes the problem but I've had this glitch two times now. 

Occurred when duplicating a npc 

Probably 60+ npcs some with images for the profile pictures

Had duplicated many npcs all of kinds with images etc no idea what causes the crashes to happen. Both times happened with many npcs stored and duplicating (potentially long named npcs) but can't be sure if npc count or name is the factor  since duplicates work fine a lot of the time

**Comment by fmasa** [comment]
Hi @happydoggoo, can you first try clearing the app cache?

I will investigate as I got similar bug report and I want to fix this for good. 🙂

**Comment by happydoggoo** [comment]
Still crashes on the selection of the npc tab

**Comment by fmasa** [comment]
I see some new error reports for NPC with name longer than 50 characters for a user with Samsung S20+ and I suspect that this might be you.

I think I found the issue and will prepare a fix in the evening (in ~5 hours). @happydoggoo Can you provide the name of the party, so I can fix the data as well?

Notes for fix:
- Max name length is 50 characters (It could make sense to increase this)
- Character name is validated when editing Character from the app, so the likely culprit is Character duplication - this sidesteps the DB schema validation, because it's implemented in the cloud function.
- Character name length should be validated in https://github.com/fmasa/wfrp-master/blob/7f02e38b3afb7fe1224d3d91276403342750276e/functions/src/functions/duplicateCharacter.ts#L13
- [`duplicateName()`](https://github.com/fmasa/wfrp-master/blob/7f02e38b3afb7fe1224d3d91276403342750276e/common/src/commonMain/kotlin/cz/frantisekmasa/wfrp_master/common/core/utils/DuplicateName.kt#L3) should take length argument and do something smarter than just appending ` (Copy)` - ideally trimming the original name if necessary.

**Comment by happydoggoo** [comment]
Parties name is Party

**Comment by fmasa** [comment]
@happydoggoo I fixed the data in your Party (you may need to clear the cache now) and added checks that will prevent this in the future (#364)
